// // nodemailer package use to sent mail


// const nodemailer = require('nodemailer')

// const transporter = nodemailer.createTransport({
//     service: 'gmail',
//     auth:{
//         user: "kabinshrestha377@gmail.com",
//         pass: "qclwrwxbbjfhqnic"  // App password not gmail password
//     }

// });

// const mailObject = {
//     from:  "kabinshrestha377@gmail.com",
//     to: "mpsandip12@gmail.com",

//     subject: "This is generated by me..",
//     text: "Web development class tutorial"
// };

// transporter.sendMail(mailObject, (err, info) => {
//     if(err) {
//         console.log(err);
//     }
//     else{
//         console.log("Email send.");
//         console.log(info);
//     }
// });