const event = require('events');
let eventEmitter = new event.EventEmitter();
const nodemailer = require('nodemailer');

// eventEmitter.on('sendMail', () => {
//     console.log('An Email has been sent');
// });

// function singup(){
//     // related to sign up function
//     eventEmitter.emit('sendMail');
// }

// singup();


// to sent mail to user to sign up (s/he is signup by printing his/her name)
// eventEmitter.on('userjoin' , (name) => {
//     console.log(name + " has been sign up to Gmail.")
// });

// function newUserJoin(name){
//     eventEmitter.emit('userjoin', name);
// }

// newUserJoin('Kabin');

// sending mail using eventemitter.


eventEmitter.on('sendMail', () => {
    const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth:{
            user: "kabinshrestha377@gmail.com",
            pass: "qclwrwxbbjfhqnic"  // App password not gmail password
        }
    
    });
    
    const mailObject = {
        from:  "kabinshrestha377@gmail.com",
        to: "mpsandip12@gmail.com",
    
        subject: "This is generated by me..",
        text: "Web development class tutorial"
    };
    
    transporter.sendMail(mailObject, (err, info) => {
        if(err) {
            console.log(err);
        }
        else{
            console.log("Email send.");
            console.log(info);
        }
    });
});

function singup(){
    // related to sign up function
    eventEmitter.emit('sendMail');
}

singup();
